# Task proposal


Explore various features and concepts of pandas and numpy in a practical way through a python for data science course.

Course: [Python for Data Science and Machine Learning](https://www.udemy.com/course/python-para-data-science-e-machine-learning/)

Sections: Jupyter Notebook; Python for Data Analysis - Numpy; Python for Data Analysis - Pandas; Python for data analysis - Pandas Exercises. (3 hours and 30 minutes)

# Jupyter Notebook


The jupyter notebook is a way to run python codes in cell shapes, allowing you to separate the codes and even include texts between them.


In the course, the teacher shows shortcuts and ways to execute the different cells.


## Virtual Environment


Different Python codes can use different libraries in their composition, for example, for the Data Science area, it is common to use a set of libraries such as Pandas, Numpy, Matplotlib and others.


A virtual environment is a place designed to execute Python code that takes into account the libraries used in that specific code, ensuring that only those libraries in their specific versions are used. The libraries present within an environment are defined by the programmer.


This is a way to ensure that the project uses only the necessary space and that it is also in the right versions of the libraries.

# Python for Numpy analysis

Numpy is a library focused on linear algebra for Python, allowing you to perform operations with vectors and matrices.

It is imported into the code as written below.

In [ ]:
import numpy as np

## Initializing vectors

The codes below show different ways to initialize a numpy array.

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [ ]:
np.random.rand(2,2)

array([[0.78837854, 0.75624333],
       [0.7401366 , 0.67890463]])

In [ ]:
np.random.randn(2,2)

array([[-1.30416762,  0.82855194],
       [ 0.41735296, -0.25007776]])

In [ ]:
np.random.randint(0, 100, 10)

array([87,  3, 83, 79, 17, 82, 48, 14, 77, 86])

## Methods in numpy

In [ ]:
arr = np.random.rand(25)
arr

array([0.5152997 , 0.32525752, 0.90711265, 0.78652814, 0.76314719,
       0.67489299, 0.08757781, 0.04185605, 0.35382686, 0.71954054,
       0.64552923, 0.69145667, 0.196686  , 0.8205705 , 0.35922499,
       0.17345051, 0.28558158, 0.52485839, 0.08401569, 0.3812755 ,
       0.29098548, 0.10554907, 0.55514454, 0.87110986, 0.9366895 ])

In [ ]:
arr = arr.reshape(5, 5)
arr

array([[0.5152997 , 0.32525752, 0.90711265, 0.78652814, 0.76314719],
       [0.67489299, 0.08757781, 0.04185605, 0.35382686, 0.71954054],
       [0.64552923, 0.69145667, 0.196686  , 0.8205705 , 0.35922499],
       [0.17345051, 0.28558158, 0.52485839, 0.08401569, 0.3812755 ],
       [0.29098548, 0.10554907, 0.55514454, 0.87110986, 0.9366895 ]])

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr.max()

0.9366894967578038

In [ ]:
arr.min()

0.04185604504107354

In [ ]:
arr.argmax()

24

## Indexing

In [ ]:
arr = np.arange(0, 30, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
arr[5]

15

In [ ]:
arr[5:9]

array([15, 18, 21, 24])

In [ ]:
arr[:9]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [ ]:
arr[6:]

array([18, 21, 24, 27])

In [ ]:
arr[3:] = 9
arr

array([0, 3, 6, 9, 9, 9, 9, 9, 9, 9])

### Two-dimensional arrays

In [ ]:
arr = np.arange(50).reshape((5, 10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

To copy one array to another, the copy method must be used, otherwise you will be referencing the same space in memory to two different arrays

In [ ]:
arr2 = arr[:3].copy()
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

## Numpy array operations

In [ ]:
arr = np.arange(0, 16)
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [ ]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [ ]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [ ]:
np.mean(arr)

7.5

In [ ]:
np.std(arr)

4.6097722286464435

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [ ]:
np.min(arr)

0

Other operations can be seen at: https://numpy.org/doc/stable/reference/ufuncs.html

## Exercises

Create an array of 10 zeros

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of 10 ones

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives

In [ ]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create an array of integers from 10 to 50

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of even numbers from 10 to 50

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

I created a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate random numbers between 0 and 1

In [ ]:
np.random.rand(1)

array([0.28558273])

Use Numpy to generate an array of 25 random numbers drawn from a normal distribution.

In [ ]:
np.random.randn(25)

array([ 1.20022414, -2.30410639,  0.90730957,  0.53967123, -0.61995616,
       -1.47939995, -0.35826492,  1.0423463 ,  0.37326339,  0.99839196,
        0.78402795, -0.72063318, -0.56345237, -0.97061301,  1.56680768,
        0.42534891,  0.76670663,  0.83324134,  1.96691008,  0.62474841,
        1.05257848, -0.18097492, -0.17817459, -1.36331702,  1.15993521])

Create the following matrix:

In [ ]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Create an array of size 20 equally spaced between 0 and 1.

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

You will now be given some matrices and asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[3,4]

20

In [ ]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [ ]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Get the sum of all values in "mat"

In [ ]:
mat.sum()

325

Get the standard deviation of the values in mat

In [ ]:
mat.std()

7.211102550927978

Get the sum of all columns in mat

In [ ]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Python for data analysis - Pandas

Pandas is a library for data manipulation and cleaning, similar to excel.

Pandas have internal data structures, which are explained in the next two topics.

## Series

In pandas, a series would be the equivalent of a 1-d array, however, obtaining an index.

In [ ]:
import numpy as np
import pandas as pd

labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [ ]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

### Series

In [ ]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [ ]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

### Using an index

In [ ]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])

In [ ]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [ ]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','USSR', 'Japan'])

In [ ]:
ser2

USA        1
Germany    2
USSR       5
Japan      4
dtype: int64

In [ ]:
ser1['USA']

1

In [ ]:
ser1 + ser2

USA        2
Germany    4
USSR       8
Japan      8
dtype: int64

##DataFrame

The DataFrame is a structure capable of storing two-dimensional structures.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from numpy.random import randn
np.random.seed(101)

In [ ]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

### Selection and indexing

In [ ]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [ ]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

DataFrame columns are Series

In [ ]:
type(df['W'])

pandas.core.series.Series

In [ ]:
df['new'] = df['W'] + df['Y']

In [ ]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

Removing columns

In [ ]:
df.drop('new',axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [ ]:
df.drop('new',axis=1,inplace=True)

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

Another way to delete columns:

In [ ]:
df.drop('E',axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

Selecting lines

In [ ]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [ ]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

Subset of rows and columns

In [ ]:
df.loc['B','Y']

-0.8480769834036315

In [ ]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

### Conditional selection

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df>0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [ ]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [ ]:
df[df['W']>0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [ ]:
df[(df['W']>0) & (df['Y'] > 1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [ ]:
novoind = 'CA NY WY OR CO'.split()

In [ ]:
df['states'] = novoind

In [ ]:
df

W         X         Y         Z states
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [ ]:
df.set_index('states')

W         X         Y         Z
states                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [ ]:
df

W         X         Y         Z states
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [ ]:
df.set_index('states',inplace=True)

In [ ]:
df

W         X         Y         Z
states                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

### Index hierarchy and multiple indexes

The code below represents a Multi-Indexed DataFrame:

In [ ]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside)) # Zip method will take two lists and 'link' the indexes into tuples
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [ ]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [ ]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

The same can also be accessed using loc and iloc.

In [ ]:
df.loc['G1']

A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [ ]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [ ]:
df.index.names

FrozenList([None, None])

In [ ]:
df.index.names = ['group','number']

In [ ]:
df

A         B
group number                    
G1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
G2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

Another way to select content is using cross section (xs)

In [ ]:
df.xs('G1')

A         B
number                    
1       0.302665  1.693723
2      -1.706086 -1.159119
3      -0.134841  0.390528

In [ ]:
df.xs(1,level='number')

A         B
group                    
G1     0.302665  1.693723
G2     0.166905  0.184502

### Missing data
Missing values in Python can be represented by numpy's 'nan' data type, as shown in the code below.

In [ ]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [ ]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

One of the ways to handle missing data is using dropna.

In [ ]:
df.dropna()

A    B  C
0  1.0  5.0  1

Deleting the columns:

In [ ]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [ ]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

Another way is to fill in the values with fillna.

In [ ]:
df.fillna(value='content')

A        B  C
0      1.0      5.0  1
1      2.0  content  2
2  content  content  3

Replacing values with the average of the column values.

In [ ]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

Replacing the missing values with the previous values.

In [ ]:
df.fillna(method='ffill')

A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3

### Grouping data

The Groupby method should be used when there is a need to group a set of data and apply some function to them.

For example, grouping the sales of each salesperson in a store and adding them all together to find out the total profit.

In [ ]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
        'Name':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
        'Sale':[200,120,340,124,243,350]}

df = pd.DataFrame(data)
df

Company     Name  Sale
0    GOOG      Sam   200
1    GOOG  Charlie   120
2    MSFT      Amy   340
3    MSFT  Vanessa   124
4      FB     Carl   243
5      FB    Sarah   350

In [ ]:
by_company = df.groupby('Company')

In [ ]:
 by_company['Sale'].mean()

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sale, dtype: float64

In [ ]:
 by_company['Sale'].std()

Company
FB       75.660426
GOOG     56.568542
MSFT    152.735065
Name: Sale, dtype: float64

In [ ]:
 by_company['Sale'].min()

Company
FB      243
GOOG    120
MSFT    124
Name: Sale, dtype: int64

In [ ]:
 by_company['Sale'].max()

Company
FB      350
GOOG    200
MSFT    340
Name: Sale, dtype: int64

In [ ]:
 by_company['Sale'].count()

Company
FB      2
GOOG    2
MSFT    2
Name: Sale, dtype: int64

In [ ]:
by_company['Sale'].describe()

count   mean         std    min     25%    50%     75%    max
Company                                                               
FB         2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG       2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT       2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [ ]:
by_company.describe().transpose()

Company             FB        GOOG        MSFT
Sale count    2.000000    2.000000    2.000000
     mean   296.500000  160.000000  232.000000
     std     75.660426   56.568542  152.735065
     min    243.000000  120.000000  124.000000
     25%    269.750000  140.000000  178.000000
     50%    296.500000  160.000000  232.000000
     75%    323.250000  180.000000  286.000000
     max    350.000000  200.000000  340.000000

In [ ]:
by_company.describe().transpose()['GOOG']

Sale  count      2.000000
      mean     160.000000
      std       56.568542
      min      120.000000
      25%      140.000000
      50%      160.000000
      75%      180.000000
      max      200.000000
Name: GOOG, dtype: float64

### Concatenation, joining and merging

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [ ]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

In [ ]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

#### Concatenation

In [ ]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

#### Merge

Enables the merging of dataframes that have an element in common.

In [ ]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
pd.merge(left, right, on=['key1', 'key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [ ]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [ ]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [ ]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

#### Join

In [ ]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2'])

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [ ]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [ ]:
left.join(right, how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

### Operations

In [ ]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [ ]:
df['col2'].unique()

array([444, 555, 666])

In [ ]:
df['col2'].nunique()

3

In [ ]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [ ]:
def times2(x):
    return x*2

In [ ]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [ ]:
del df['col1']

In [ ]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [ ]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df.sort_values(by='col2') #inplace=False by default

col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

In [ ]:
df.isnull()

col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [ ]:
df.dropna()

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [ ]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [ ]:
df.fillna('fill')

col1   col2 col3
0   1.0   fill  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3  fill  444.0  xyz

In [ ]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [ ]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [ ]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

### Data input and output

CSV

In [ ]:
df = pd.read_csv('example.csv')

df.to_csv('example.csv',index=False)

Excel

In [ ]:
pd.read_excel('example.xlsx',sheetname='Sheet1')

df.to_excel('example.xlsx',sheet_name='Sheet1')

# Python for analysis (pandas exercises)

## Exercise 1

In [ ]:
import pandas as pd

In [ ]:
sal = pd.read_csv("/content/Salaries.csv")

In [ ]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

     Year  Notes         Agency  Status  
0  2011.0    NaN  San Francisco     NaN  
1  2011.0    NaN  San Francisco     NaN  
2  2011.0    NaN  San Francisco     NaN  
3  2011.0    NaN  San Francisco     NaN  
4  2011.0    NaN  San Francisco     NaN

### Finding out how many entries there are

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19923 entries, 0 to 19922
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Id                19923 non-null  int64  
 1   EmployeeName      19923 non-null  object 
 2   JobTitle          19922 non-null  object 
 3   BasePay           19922 non-null  float64
 4   OvertimePay       19922 non-null  float64
 5   OtherPay          19922 non-null  float64
 6   Benefits          0 non-null      float64
 7   TotalPay          19922 non-null  float64
 8   TotalPayBenefits  19922 non-null  float64
 9   Year              19922 non-null  float64
 10  Notes             0 non-null      float64
 11  Agency            19922 non-null  object 
 12  Status            0 non-null      float64
dtypes: float64(9), int64(1), object(3)
memory usage: 2.0+ MB


### What is the average "BasePay"?

In [ ]:
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce')

sal['BasePay'].mean()

92255.34896948097

### What is the largest amount of "OvertimePay" in the dataset?

In [ ]:
sal['OvertimePay'] = pd.to_numeric(sal['OvertimePay'], errors='coerce')

sal['OvertimePay'].max()

245131.88

### What is JOSEPH DRISCOLL's job title?

In [ ]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

### How much does JOSEPH DISCOLL earn (including benefits)

In [ ]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

### What is the name of the highest paid person (including benefits)?

In [ ]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]['EmployeeName']

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [ ]:
sal.loc[sal['TotalPayBenefits'].idxmax()]

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                        2011.0
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

### What is the name of the person who is paid the least (including benefits)? Do you notice anything strange about how much he or she is paid?

In [ ]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]['EmployeeName']

19921    CHARLES BRIDGEWATER
Name: EmployeeName, dtype: object

### How many unique job titles are there?

In [ ]:
sal['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC',
       'DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)',
       'ASSISTANT DEPUTY CHIEF II', 'BATTALION CHIEF, (FIRE DEPARTMENT)',
       'DEPUTY DIRECTOR OF INVESTMENTS',
       'CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)',
       'ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)',
       'EXECUTIVE CONTRACT EMPLOYEE', 'DEPARTMENT HEAD V',
       'COMMANDER III, (POLICE DEPARTMENT)',
       'CAPTAIN, EMERGENCYCY MEDICAL SERVICES',
       'ASSISTANT MEDICAL EXAMINER', 'CAPTAIN, FIRE SUPPRESSION',
       'CHIEF OF POLICE', 'DEPUTY CHIEF III (POLICE DEPARTMENT)',
       'INSPECTOR III, (POLICE DEPARTMENT)',
       'ELECTRONIC MAINTENANCE TECHNICIAN',
       'ADMINISTRATOR, SFGH MEDICAL CENTER',
       'LIEUTENANT III (POLICE DEPARTMENT)', 'FIREFIGHTER',
       'NURSING SUPERVISOR PSYCHIATRIC', 'MAYOR',
       'LIEUTENANT, FIRE DEPARTMENT', 'INCIDENT 

### What are the top 5 most common jobs?

In [ ]:
sal['JobTitle'].value_counts()[:5]

JobTitle
TRANSIT OPERATOR      1463
REGISTERED NURSE      1082
FIREFIGHTER            744
POLICE OFFICER III     743
DEPUTY SHERIFF         653
Name: count, dtype: int64

### How many job titles were held by just one person in 2013?

In [ ]:
sal[sal['Year'] == '2013']

Empty DataFrame
Columns: [Id, EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year, Notes, Agency, Status]
Index: []

### How many people have the word Boss in their title?

In [ ]:
def chief_string(title):
  if 'chief' in title.lower():
    return True
  else:
    return False


In [ ]:
sum(sal['JobTitle'].astype(str).apply(lambda x: boss_string(x)))

627


### Is there a correlation between job title string length and salary?

In [ ]:
sal['String size'] = sal['JobTitle'].astype(str).apply(len)

In [ ]:
sal[['String size', 'TotalPayBenefits']].corr()

String size  TotalPayBenefits
String size          1.000000          0.016534
TotalPayBenefits     0.016534          1.000000

## Exercise 2

In [ ]:
import pandas as pd

In [ ]:
ecom = pd.read_csv('Ecommerce Purchases')

### Check the 'head' of the DataFrame

In [ ]:
ecom.head()

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4  Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   
3  Williams, Marshall and Buchanan  6011578504430710       02/24   
4        Brown, Watson and Andrews  6011456623207998       10/25   

   CC Security Code                  CC Provider  \
0               900                 JCB 16 digit   
1               561                   Mastercard   
2               699                 JCB 16 digit   
3               384                     Discover   
4               678  Diners Club / Carte Blanche   

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development   
1              anthony41@reed.com                       Drilling engineer   
2  amymiller@morales-harrison.com                Customer service manager   
3     brent16@olson-robinson.info                       Drilling engineer   
4     christopherwright@gmail.com                             Fine artist   

        IP Address Language  Purchase Price  
0  149.146.147.205       el           98.14  
1     15.160.41.51       fr           70.73  
2   132.207.160.22       de            0.95  
3     30.250.74.19       es           78.04  
4     24.140.33.94       es           77.82

### How many rows and columns are there?

In [ ]:
ecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Address           10000 non-null  object 
 1   Lot               10000 non-null  object 
 2   AM or PM          10000 non-null  object 
 3   Browser Info      10000 non-null  object 
 4   Company           10000 non-null  object 
 5   Credit Card       10000 non-null  int64  
 6   CC Exp Date       10000 non-null  object 
 7   CC Security Code  10000 non-null  int64  
 8   CC Provider       10000 non-null  object 
 9   Email             10000 non-null  object 
 10  Job               10000 non-null  object 
 11  IP Address        10000 non-null  object 
 12  Language          10000 non-null  object 
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


### What is the average purchase price?

In [ ]:
ecom['Purchase Price'].mean()

50.347302

### What were the highest and lowest purchase prices?

In [ ]:
ecom['Purchase Price'].max()

99.99

In [ ]:
ecom['Purchase Price'].min()

0.0

### How many people have English 'en' as their language of choice on the site?

In [ ]:
ecom[ecom['Language'] == 'en'].shape

(1098, 14)

### How many people are in the position of Lawyer?

In [ ]:
ecom[ecom['Job'] == 'Lawyer'].shape

(30, 14)

###How many people made the purchase during the AM and how many during the PM?

In [ ]:
ecom['AM or PM'].value_counts()

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

### What are the 5 most common types of jobs?

In [ ]:
ecom['Job'].value_counts()[:5]

Job
Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Purchasing manager               27
Designer, jewellery              27
Name: count, dtype: int64

### Someone made a purchase that came from Lot: "90 WT", what was the purchase price for this transaction?

In [ ]:
ecom[ecom['Lot'] == '90 WT']['Purchase Price']

513    75.1
Name: Purchase Price, dtype: float64

### What is the email address of the person with the following credit card number: 4926535242672853

In [ ]:
ecom[ecom['Credit Card'] == 4926535242672853]['Email']

1234    bondellen@williams-garza.com
Name: Email, dtype: object

### How many people have American Express as their credit card provider and have made a purchase over $95?

In [ ]:
ecom[(ecom['CC Provider'] == 'American Express') & (ecom['Purchase Price'] > 95.0)].shape

(39, 14)

### How many people have a credit card that expires in 2025?

In [ ]:
sum(ecom['CC Exp Date'].apply(lambda x: x[3:]) == '25')

1033

### What are the top 5 most popular email providers/hosts (e.g. gmail.com, yahoo.com, etc)

In [ ]:
ecom['Email'].apply(lambda x: x.split('@')[1]).value_counts().head()

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64