# Proposta da tarefa


Explorar diversas funcionalidades e conceitos de pandas e numpy de uma forma prática através de um curso de python para data science.

Curso: [Python para Data Science e Machine Learning](https://www.udemy.com/course/python-para-data-science-e-machine-learning/)

Seções: Jupyter Notebook; Python para Análise de dados - Numpy; Python para Análise de dados - Pandas; Python para análise de dados - Exercícios Pandas. (3 horas e 30 minutos)



# Jupyter Notebook


O jupyter notebook é uma forma de executar códigos em python em formas de células, permitindo separar os códigos e até mesmo incluir textos entre eles.


No curso, o professor mostra os atalhos e formas de executar as diferentes células.


## Ambiente Virtuais


Diferentes códigos em python podem usar diferentes bibliotecas em sua composição, por exemplo, para a área de Data Science, é comum o uso de um conjunto de bibliotecas como a Pandas, Numpy, Matplotlib e entre outros.


Um ambiente virtual é um lugar destinado a executar códigos em python que leva em consideração as bibliotecas usadas naquele código em específico, fazendo com que apenas essas bibliotecas em suas determinadas versões sejam usadas. As bibliotecas presentes dentro de um ambiente são definidas pelo programador.


Essa é uma forma de garantir que o projeto use apenas o espaço necessário e que também esteja nas versões certa das bibliotecas.

# Python para análise Numpy

A numpy é uma biblioteca com foco em álgebra linear para python, permitindo realizar operações com vetores e matrizes.

Ela é importada para o código conforme escrito abaixo.

In [ ]:
import numpy as np

## Inicializando vetores

Os códigos abaixo mostram diferentes formas de se inicializar um array numpy.

In [ ]:
minha_lista = [1,2,3]
minha_lista

[1, 2, 3]

In [ ]:
np.array(minha_lista)

array([1, 2, 3])

In [ ]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [ ]:
np.random.rand(2,2)

array([[0.55554211, 0.14674752],
       [0.73818409, 0.83024691]])

In [ ]:
np.random.randn(2,2)

array([[-1.73149556, -1.39229059],
       [ 0.41447113,  0.66915119]])

In [ ]:
np.random.randint(0, 100, 10)

array([56, 51,  3, 91, 89,  8, 55, 96, 41, 29])

## Métodos na numpy


In [ ]:
arr = np.random.rand(25)
arr

array([0.91835557, 0.89108126, 0.20114819, 0.49963115, 0.39608165,
       0.34263803, 0.20669444, 0.16117437, 0.96640195, 0.66821322,
       0.86212201, 0.54967095, 0.92824006, 0.24890945, 0.62447715,
       0.37789362, 0.13016373, 0.66020518, 0.86659534, 0.12390828,
       0.38870451, 0.39370109, 0.77143169, 0.13844498, 0.80655742])

In [ ]:
arr = arr.reshape(5, 5)
arr

array([[0.91835557, 0.89108126, 0.20114819, 0.49963115, 0.39608165],
       [0.34263803, 0.20669444, 0.16117437, 0.96640195, 0.66821322],
       [0.86212201, 0.54967095, 0.92824006, 0.24890945, 0.62447715],
       [0.37789362, 0.13016373, 0.66020518, 0.86659534, 0.12390828],
       [0.38870451, 0.39370109, 0.77143169, 0.13844498, 0.80655742]])

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr.max()

0.9664019459862591

In [ ]:
arr.min()

0.12390827751559086

In [ ]:
arr.argmax()

8

## Indexação

In [ ]:
arr = np.arange(0, 30, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
arr[5]

15

In [ ]:
arr[5:9]

array([15, 18, 21, 24])

In [ ]:
arr[:9]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [ ]:
arr[6:]

array([18, 21, 24, 27])

In [ ]:
arr[3:] = 9
arr

array([0, 3, 6, 9, 9, 9, 9, 9, 9, 9])

### Arrays bidimensionais

In [ ]:
arr = np.arange(50).reshape((5, 10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

Para copiar um array em outro, o método copy deve ser usado, caso contrário, estará refenciando o mesmo espaço na memória para dois arrays diferentes

In [ ]:
arr2 = arr[:3].copy()
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

## Operações dos arrays numpy

In [ ]:
arr = np.arange(0, 16)
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [ ]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [ ]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [ ]:
np.mean(arr)

7.5

In [ ]:
np.std(arr)

4.6097722286464435

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [ ]:
np.min(arr)

0

Outras operações podem ser vistas em: https://numpy.org/doc/stable/reference/ufuncs.html

## Exercícios

Crie uma matriz de 10 zeros

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Crie uma matriz de 10 ones


In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Crie uma matriz de 10 cincos

In [ ]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Crie um array de inteiros de 10 até 50

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Crie um array dos numeros pares de 10 até 50

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Criei uma matriz 3x3 com valores variando de 0 até 8

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Crie uma matriz identidade 3x3

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy para gerar números aleatórios entre 0 e 1

In [ ]:
np.random.rand(1)

array([0.61998195])

Use Numpy para gerar um array de 25 números aleatórios tirados de uma distribuição normal.

In [ ]:
np.random.randn(25)

array([ 0.05876479, -0.30954721, -0.44925735, -0.6456689 ,  1.013913  ,
       -1.50207037,  0.24152316, -0.29027236, -0.05992998,  0.31067286,
       -0.26369989, -0.04559701, -0.14954586, -0.72680815,  1.22126122,
        1.1532238 ,  0.77461041, -0.59096221,  1.04404639,  0.28789793,
       -1.45272699,  0.89173885,  1.28207904,  0.47061931,  0.82287015])

Crie a seguinte matriz:

In [ ]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Crie um array de tamanho 20 igualmente espaçado entre 0 e 1.

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Agora você receberá algumas matrizes e será solicitado a replicar as saídas resultantes da matriz:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[3,4]

20

In [ ]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [ ]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Obter a soma de todos os valores no "mat"

In [ ]:
mat.sum()

325

Obter o desvio padrão dos valores em mat

In [ ]:
mat.std()

7.211102550927978

Obter a soma de todas as colunas em mat

In [ ]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Python para análise de dados - Pandas

Pandas é uma biblioteca para manipulação e limpeza de dados, semelhante ao excel.

Os Pandas possui estruturas de dados internas, as quais são explicadas nos próximos dois tópicos.

## Series

Em pandas, uma series seria o equivalente a um array 1-d, porém, obtendo um indice.

In [ ]:
import numpy as np
import pandas as pd

labels = ['a','b','c']
minha_lista = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [ ]:
pd.Series(data=minha_lista)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(data=minha_lista,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(minha_lista,labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

### Dados nas Series

In [ ]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [ ]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

### Usando um índice

In [ ]:
ser1 = pd.Series([1,2,3,4],index = ['EUA', 'Alemanha','USSR', 'Japão'])

In [ ]:
ser1

EUA         1
Alemanha    2
USSR        3
Japão       4
dtype: int64

In [ ]:
ser2 = pd.Series([1,2,5,4],index = ['EUA', 'Alemanha','Italia', 'Japão'])

In [ ]:
ser2

EUA         1
Alemanha    2
Italia      5
Japão       4
dtype: int64

In [ ]:
ser1['EUA']

1

In [ ]:
ser1 + ser2

Alemanha    4.0
EUA         2.0
Italia      NaN
Japão       8.0
USSR        NaN
dtype: float64

## DataFrame

O DataFrame é um estrutura capaz de armazenar estruturas bidimensionais.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from numpy.random import randn
np.random.seed(101)

In [ ]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

### Seleção e indexação

In [ ]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [ ]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

As colunas dos DataFrames são Series

In [ ]:
type(df['W'])

pandas.core.series.Series

In [ ]:
df['new'] = df['W'] + df['Y']

In [ ]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

Removendo colunas

In [ ]:
df.drop('new',axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [ ]:
df.drop('new',axis=1,inplace=True)

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

Outra forma de deletar colunas:

In [ ]:
df.drop('E',axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

Selecionando linhas

In [ ]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [ ]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

Subconjunto de linhas e colunas

In [ ]:
df.loc['B','Y']

-0.8480769834036315

In [ ]:
df.loc[['A','B'],['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

### Seleção condicional

In [ ]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df>0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [ ]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [ ]:
df[df['W']>0][['Y','X']]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [ ]:
df[(df['W']>0) & (df['Y'] > 1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [ ]:
novoind = 'CA NY WY OR CO'.split()

In [ ]:
df['Estados'] = novoind

In [ ]:
df

W         X         Y         Z Estados
A  2.706850  0.628133  0.907969  0.503826      CA
B  0.651118 -0.319318 -0.848077  0.605965      NY
C -2.018168  0.740122  0.528813 -0.589001      WY
D  0.188695 -0.758872 -0.933237  0.955057      OR
E  0.190794  1.978757  2.605967  0.683509      CO

In [ ]:
df.set_index('Estados')

W         X         Y         Z
Estados                                        
CA       2.706850  0.628133  0.907969  0.503826
NY       0.651118 -0.319318 -0.848077  0.605965
WY      -2.018168  0.740122  0.528813 -0.589001
OR       0.188695 -0.758872 -0.933237  0.955057
CO       0.190794  1.978757  2.605967  0.683509

In [ ]:
df

W         X         Y         Z Estados
A  2.706850  0.628133  0.907969  0.503826      CA
B  0.651118 -0.319318 -0.848077  0.605965      NY
C -2.018168  0.740122  0.528813 -0.589001      WY
D  0.188695 -0.758872 -0.933237  0.955057      OR
E  0.190794  1.978757  2.605967  0.683509      CO

In [ ]:
df.set_index('Estados',inplace=True)

In [ ]:
df

W         X         Y         Z
Estados                                        
CA       2.706850  0.628133  0.907969  0.503826
NY       0.651118 -0.319318 -0.848077  0.605965
WY      -2.018168  0.740122  0.528813 -0.589001
OR       0.188695 -0.758872 -0.933237  0.955057
CO       0.190794  1.978757  2.605967  0.683509

### Hierarquia de índices e índices múltiplos

O código abaixo representa um DataFrame Multi-Indexado:

In [ ]:
# Níveis de Índice
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))    # Método zip irá pegar duas lista e 'linkar' os indices em tuplas
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [ ]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [ ]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

O mesmo poode ser acessado usando também o  loc e iloc.

In [ ]:
df.loc['G1']

A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [ ]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [ ]:
df.index.names

FrozenList([None, None])

In [ ]:
df.index.names = ['Grupo','Número']

In [ ]:
df

A         B
Grupo Número                    
G1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
G2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

Outra forma de seleciona conteúdos é usando o cross section (xs)

In [ ]:
df.xs('G1')

A         B
Número                    
1       0.302665  1.693723
2      -1.706086 -1.159119
3      -0.134841  0.390528

In [ ]:
df.xs(['G1',1])

<ipython-input-137-c549ee06ce91>:1: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  df.xs(['G1',1])


A    0.302665
B    1.693723
Name: (G1, 1), dtype: float64

In [ ]:
df.xs(1,level='Número')

A         B
Grupo                    
G1     0.302665  1.693723
G2     0.166905  0.184502

### Dados faltantes

Valores faltantes em python podem ser representaods pelo tipo de dado 'nan' de numpy, como mostra o código abaixo.

In [ ]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [ ]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

Umas das formas de tratar dados faltantes é usando o dropna.


In [ ]:
df.dropna()

A    B  C
0  1.0  5.0  1

Excluindo as colunas:

In [ ]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [ ]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

Outra forma é preencher os valores com fillna.

In [ ]:
df.fillna(value='Conteúdo')

A         B  C
0       1.0       5.0  1
1       2.0  Conteúdo  2
2  Conteúdo  Conteúdo  3

Substituindo valores pela média dos valores da coluna.

In [ ]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

Substituindo os valores faltantes pelos valores anteriores.

In [ ]:
df.fillna(method='ffill')

A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  2.0  5.0  3

### Agrupando dados

O método Groupby deve ser usado quando há a necessidade de agrupar conjunto de dados e aplicar alguma função neles.

Por exemplo, agrupar as vendas de cada vendedor de uma loja e somar tudo para saber o ganho total.

In [ ]:
data = {'Empresa':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Nome':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Venda':[200,120,340,124,243,350]}

df = pd.DataFrame(data)
df

Empresa     Nome  Venda
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [ ]:
por_companhia = df.groupby('Empresa')

In [ ]:
por_companhia.mean()

<ipython-input-16-52e1613a4d27>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  por_companhia.mean()


Venda
Empresa       
FB       296.5
GOOG     160.0
MSFT     232.0

In [ ]:
por_companhia.std()

<ipython-input-17-381eba34329f>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  por_companhia.std()


Venda
Empresa            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [ ]:
por_companhia.min()

Nome  Venda
Empresa                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [ ]:
por_companhia.max()

Nome  Venda
Empresa                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [ ]:
por_companhia.count()

Nome  Venda
Empresa             
FB          2      2
GOOG        2      2
MSFT        2      2

In [ ]:
por_companhia.describe()

Venda                                                        
        count   mean         std    min     25%    50%     75%    max
Empresa                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [ ]:
por_companhia.describe().transpose()

Empresa              FB        GOOG        MSFT
Venda count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [ ]:
por_companhia.describe().transpose()['GOOG']

Venda  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64

### Concatenação, junção e mesclagem

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [ ]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

In [ ]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

#### Concatenação

In [ ]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

#### Mesclagem

Possibilita a mesclagem de dataframes que possuem um elemento em comum.

In [ ]:
esquerda = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

direita = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
pd.merge(esquerda, direita, on=['key1', 'key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [ ]:
pd.merge(esquerda, direita, how='outer', on=['key1', 'key2'])

key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [ ]:
pd.merge(esquerda, direita, how='right', on=['key1', 'key2'])

key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [ ]:
pd.merge(esquerda, direita, how='left', on=['key1', 'key2'])

key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

#### Juntar

In [ ]:
esquerda = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2'])

direita = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [ ]:
esquerda.join(direita)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [ ]:
esquerda.join(direita, how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

### Operações

In [ ]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [ ]:
df['col2'].unique()

array([444, 555, 666])

In [ ]:
df['col2'].nunique()

3

In [ ]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [ ]:
def times2(x):
    return x*2

In [ ]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [ ]:
del df['col1']

In [ ]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [ ]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df.sort_values(by='col2') #inplace=False por padrão

col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

In [ ]:
df.isnull()

col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [ ]:
df.dropna()

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [ ]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [ ]:
df.fillna('Preencher')

col1       col2 col3
0        1.0  Preencher  abc
1        2.0      555.0  def
2        3.0      666.0  ghi
3  Preencher      444.0  xyz

In [ ]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [ ]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [ ]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

### Entrada e saída de dados

CSV

In [ ]:
df = pd.read_csv('exemplo.csv')

df.to_csv('exemplo.csv',index=False)

Excel

In [ ]:
pd.read_excel('Exemplo_Excel.xlsx',sheetname='Sheet1')

df.to_excel('Exemplo_Excel.xlsx',sheet_name='Sheet1')

# Python para análise (exercícios pandas)

## Exercício 1

In [ ]:
import pandas as pd

In [ ]:
sal = pd.read_csv("/content/Salaries.csv")

<ipython-input-3-bc1d40319f1e>:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.read_csv("/content/Salaries.csv")


In [ ]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

### Descobrindo quantas entradas existem

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148049 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB


### Qual o "BasePay" médio?

In [ ]:
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce') # Transformando valores não numéricos em numéricos

sal['BasePay'].mean()

66325.4488404877

### Qual é a maior quantidade de "OvertimePay" no conjunto de dados?

In [ ]:
sal['OvertimePay'] = pd.to_numeric(sal['OvertimePay'], errors='coerce') # Transformando valores não numéricos em numéricos

sal['OvertimePay'].max()

245131.88

### Qual é o cargo de JOSEPH DRISCOLL?

In [ ]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

### Quanto ganha JOSEPH DISCOLL (incluindo benefícios)

In [ ]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

### Qual o nome da pessoa mais bem paga (incluindo benefícios)?

In [ ]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]['EmployeeName']

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [ ]:
sal.loc[sal['TotalPayBenefits'].idxmax()]

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

### Qual o nome da pessoa que menos é paga (incluindo benefícios)? Você percebe algo estranho o quanto ele ou ela é paga?

In [ ]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

### Qual foi a média BasePay de todos os funcionários por ano?

In [ ]:
sal.groupby('Year').mean()['BasePay']

<ipython-input-23-a42aa5aba483>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  sal.groupby('Year').mean()['BasePay']


Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

### Quantos titulos de trabalho únicos existem?

In [ ]:
sal['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### Quais são os 5 principais empregos mais comuns?

In [ ]:
sal['JobTitle'].value_counts()[:5]

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

### Quantos títulos de trabalho foram representados por apenas uma pessoa em 2013?

In [ ]:
sal[sal['Year'] == '2013']            # Por alguma razão ele não está devolvendo o df esperado pra esse comando, não consegui avançar a partir daqui

Empty DataFrame
Columns: [Id, EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year, Notes, Agency, Status]
Index: []

### Quantas pessoas tem a palavra Chefe em seu cargo?

In [ ]:
def chief_string(title):
  if 'chief' in title.lower():
    return True
  else:
    return False


In [ ]:
sum(sal['JobTitle'].apply(lambda x: chief_string(x)))

627

### Existe uma correlação entre o comprimento da sequência do título do trabalho e o salário?

In [ ]:
sal['Tamanho da String'] = sal['JobTitle'].apply(len)

In [ ]:
sal[['Tamanho da String', 'TotalPayBenefits']].corr()

Tamanho da String  TotalPayBenefits
Tamanho da String           1.000000         -0.036878
TotalPayBenefits           -0.036878          1.000000

## Exercício 2

In [ ]:
import pandas as pd

In [ ]:
ecom = pd.read_csv('Ecommerce Purchases')

### Verifique o 'head' do DataFrame

In [ ]:
ecom.head()

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4  Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   
3  Williams, Marshall and Buchanan  6011578504430710       02/24   
4        Brown, Watson and Andrews  6011456623207998       10/25   

   CC Security Code                  CC Provider  \
0               900                 JCB 16 digit   
1               561                   Mastercard   
2               699                 JCB 16 digit   
3               384                     Discover   
4               678  Diners Club / Carte Blanche   

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development   
1              anthony41@reed.com                       Drilling engineer   
2  amymiller@morales-harrison.com                Customer service manager   
3     brent16@olson-robinson.info                       Drilling engineer   
4     christopherwright@gmail.com                             Fine artist   

        IP Address Language  Purchase Price  
0  149.146.147.205       el           98.14  
1     15.160.41.51       fr           70.73  
2   132.207.160.22       de            0.95  
3     30.250.74.19       es           78.04  
4     24.140.33.94       es           77.82

### Quantas linhas e colunas existem?

In [ ]:
ecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Address           10000 non-null  object 
 1   Lot               10000 non-null  object 
 2   AM or PM          10000 non-null  object 
 3   Browser Info      10000 non-null  object 
 4   Company           10000 non-null  object 
 5   Credit Card       10000 non-null  int64  
 6   CC Exp Date       10000 non-null  object 
 7   CC Security Code  10000 non-null  int64  
 8   CC Provider       10000 non-null  object 
 9   Email             10000 non-null  object 
 10  Job               10000 non-null  object 
 11  IP Address        10000 non-null  object 
 12  Language          10000 non-null  object 
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


### Qual o preço de compra médio?

In [ ]:
ecom['Purchase Price'].mean()

50.347302

### Quais foram os preços de compra mais altos e mais baixos?

In [ ]:
ecom['Purchase Price'].max()

99.99

In [ ]:
ecom['Purchase Price'].min()

0.0

### Quantas pessoas tem inglês 'en' como sua língua de escolha no site?

In [ ]:
ecom[ecom['Language'] == 'en'].shape

(1098, 14)

### Quantas pessoas tem o cargo de Advogado?

In [ ]:
ecom[ecom['Job'] == 'Lawyer'].shape

(30, 14)

###Quantas pessoas fizeram a compra durante AM e quantas durante PM?

In [ ]:
ecom['AM or PM'].value_counts()

PM    5068
AM    4932
Name: AM or PM, dtype: int64

### Quais são os 5 tipos de trabalhos mais comuns?

In [ ]:
ecom['Job'].value_counts()[:5]

Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Purchasing manager               27
Designer, jewellery              27
Name: Job, dtype: int64

### Alguém fez uma compra que veio do Lot: "90 WT", qual foi o preço de compra para esta transação?

In [ ]:
ecom[ecom['Lot'] == '90 WT']['Purchase Price']

513    75.1
Name: Purchase Price, dtype: float64

### Qual o email da pessoa com o seguinte número de cartão de crédito: 4926535242672853

In [ ]:
ecom[ecom['Credit Card'] == 4926535242672853]['Email']

1234    bondellen@williams-garza.com
Name: Email, dtype: object

### Quantas pessoas tem o American Express como seu fornecedor de cartão de crédito e fizeram uma compra acima de US $95?

In [ ]:
ecom[(ecom['CC Provider'] == 'American Express') & (ecom['Purchase Price'] > 95.0)].shape

(39, 14)

### Quantas pessoas tem um cartão de crédito que expira em 2025?

In [ ]:
sum(ecom['CC Exp Date'].apply(lambda x: x[3:]) == '25')

1033

### Quais são os 5 principais provedores de e-mail / hosts mais populares (por exemplo, gmail.com, yahoo.com, etc)

In [ ]:
ecom['Email'].apply(lambda x: x.split('@')[1]).value_counts().head()

hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: Email, dtype: int64